### PR TITLE
Using request and awk4 for signing.

### PR DESCRIPTION
**Pull request by trenskow**
Made it so it uses `request`s build-in AWS request signing along with package `aws4`.

### CODE REVIEW

**Comment by gyurobenjamin** [comment]
It doesn't solve my problem.
This version providing this error: Error: invalid status code from GetQueueUrl: 403. The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

**Comment by trenskow** [comment]
@gyurobenjamin This is happening to me too now.

**Comment by trenskow** [comment]
@gyurobenjamin Well it works again. Turned out, for me, it was in fact the wrong key.

**Comment by odino** [comment]
This fixed the same issue for us :)

To install:

```
    "sqs": "git+https://github.com/trenskow/sqs.git#master"
```

**Pull request merged**
